import {MEETING_POINT_TYPES} from './meetingNotes.js';
export const escapeMeetingHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export function meetingPrintHtml(note,{entityTitle='',entityType='project'}={}) {
 const e=escapeMeetingHtml;
 const raw=String(note.meeting_date||'');
 const date=/^\d{4}-\d{2}-\d{2}$/.test(raw)?raw.split('-').reverse().join('. '):raw;
 return `<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(note.title)} – verze ${e(note.version)}</title><style>
 @page{size:A4;margin:18mm}*{box-sizing:border-box}body{margin:0;background:#f1f5f9;color:#172b3a;font:14px/1.6 Arial,sans-serif}.sheet{max-width:800px;margin:16px auto;padding:36px;background:white}.brand{font-weight:bold;letter-spacing:2px;color:#345d83}.meta{color:#52616d;font-size:12px}.working{border:1px solid #cad4dd;padding:8px 12px;margin:20px 0;font-size:12px}h1{font-size:26px;line-height:1.25;margin:12px 0;overflow-wrap:anywhere}h2{font-size:16px;margin-top:24px}p{white-space:pre-wrap;overflow-wrap:anywhere}ol{padding:0;list-style:none}.point{border-top:1px solid #dbe2e8;padding:14px 0;break-inside:avoid-page}.point-label{font-size:12px;font-weight:bold;color:#426079}.reference{font-size:11px;color:#607181;overflow-wrap:anywhere}.footer{margin-top:26px;border-top:1px solid #dbe2e8;padding-top:12px;font-size:10px;color:#607181;overflow-wrap:anywhere}@media print{body{background:white}.sheet{max-width:none;margin:0;padding:0}.point{orphans:3;widows:3}}@media(max-width:500px){.sheet{padding:20px;margin:0}h1{font-size:22px}}
 </style></head><body><main class="sheet"><div class="brand">EKV · ZÁPIS Z JEDNÁNÍ</div><p class="meta">${entityType==='realization'?'Realizace':'Projekce'} · ${e(entityTitle)}</p><h1>${e(note.title)}</h1><p class="meta">Datum jednání: ${e(date)} · Uložená verze: ${e(note.version)}</p><div class="working">PRACOVNÍ ZÁPIS · Tento výstup není potvrzením schválení ani doručení účastníkům.</div><h2>Účastníci</h2><p>${e(note.participants||'Neuvedeni')}</p><h2>Body jednání</h2><ol>${(note.points||[]).map((point,index)=>`<li class="point"><div class="point-label">${index+1}. ${e(MEETING_POINT_TYPES[point.kind]||'Bod')}</div><p>${e(point.text)}</p>${point.planning_item_id?`<p class="reference">Vazba na úkol v plánu: ${e(point.planning_item_id)}</p>`:''}</li>`).join('')||'<li>Bez bodů.</li>'}</ol><footer class="footer">Zápis ${e(note.id)} · verze ${e(note.version)}<br>Obsah odpovídá uložené verzi zápisu. Aktuální stav navázaných úkolů najdete v portálu.</footer></main></body></html>`;
}
