/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './src/**/*.{js,jsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        // EKV Group brand colors - Modern palette
        brand: {
          blue: '#2764AF',
          blueLight: '#4A90E2',
          blueDark: '#1E4A7C',
          blue50: '#EFF6FF',
          blue100: '#DBEAFE',
          blue200: '#BFDBFE',
          blue300: '#93C5FD',
          blue400: '#60A5FA',
          blue500: '#3B82F6',
          blue600: '#2563EB',
          blue700: '#1D4ED8',
          blue800: '#1E40AF',
          blue900: '#1E3A8A',
          gray: '#221F1F',
          grayLight: '#6B7280',
          grayDark: '#111827',
          gray50: '#F9FAFB',
          gray100: '#F3F4F6',
          gray200: '#E5E7EB',
          gray300: '#D1D5DB',
          gray400: '#9CA3AF',
          gray500: '#6B7280',
          gray600: '#4B5563',
          gray700: '#374151',
          gray800: '#1F2937',
          gray900: '#111827',
        },
        // Modern status colors
        status: {
          success: '#10B981',
          successLight: '#34D399',
          successDark: '#059669',
          warning: '#F59E0B',
          warningLight: '#FBBF24',
          warningDark: '#D97706',
          error: '#EF4444',
          errorLight: '#F87171',
          errorDark: '#DC2626',
          info: '#3B82F6',
          infoLight: '#60A5FA',
          infoDark: '#2563EB',
        },
        // Modern accent colors
        accent: {
          purple: '#8B5CF6',
          purpleLight: '#A78BFA',
          purpleDark: '#7C3AED',
          emerald: '#10B981',
          emeraldLight: '#34D399',
          emeraldDark: '#059669',
          rose: '#F43F5E',
          roseLight: '#FB7185',
          roseDark: '#E11D48',
          amber: '#F59E0B',
          amberLight: '#FBBF24',
          amberDark: '#D97706',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        heading: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'heading-1': ['3.5rem', { lineHeight: '1.1', fontWeight: '800', letterSpacing: '-0.025em' }],
        'heading-2': ['2.5rem', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '-0.025em' }],
        'heading-3': ['2rem', { lineHeight: '1.3', fontWeight: '600', letterSpacing: '-0.025em' }],
        'heading-4': ['1.5rem', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '-0.025em' }],
        'heading-5': ['1.25rem', { lineHeight: '1.5', fontWeight: '600', letterSpacing: '-0.025em' }],
        'heading-6': ['1.125rem', { lineHeight: '1.5', fontWeight: '600', letterSpacing: '-0.025em' }],
        'display': ['4rem', { lineHeight: '1', fontWeight: '900', letterSpacing: '-0.05em' }],
        'hero': ['3rem', { lineHeight: '1.1', fontWeight: '800', letterSpacing: '-0.025em' }],
      },
      boxShadow: {
        'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
        'glass-inset': 'inset 0 1px 0 0 rgba(255, 255, 255, 0.05)',
        'neon': '0 0 5px currentColor, 0 0 10px currentColor, 0 0 15px currentColor',
        'glow': '0 0 20px rgba(59, 130, 246, 0.5)',
        'glow-lg': '0 0 40px rgba(59, 130, 246, 0.3)',
      },
      backdropBlur: {
        'xs': '2px',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};