import React,{useMemo,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Label} from '@/components/ui/label';
import {meetingPrintHtml} from '@/lib/meetingPrint';
import {saveMeetingNotePdf,sendMeetingNotePdf} from '@/lib/meetingDocumentService';

const emailsFrom = value => Array.from(new Set(String(value||'').match(/[^\s,;<>]+@[^\s,;<>]+\.[^\s,;<>]+/g)||[]));
const parseRecipients = value => Array.from(new Set(String(value||'').split(/[;,\n]/).map(v=>v.trim().toLowerCase()).filter(Boolean)));

export default function MeetingPrintDialog({note,entityTitle,entityType,entityId,entityCode,canEdit,onClose,onChanged}){
 const frame=useRef(null);const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [prepared,setPrepared]=useState(null);const [emailOpen,setEmailOpen]=useState(false);
 const [mail,setMail]=useState(()=>({recipients:emailsFrom(note.participants).join(', '),subject:`Zápis z kontrolního dne · ${entityCode||entityTitle}`,message:`Dobrý den,\n\nv příloze zasíláme zápis z kontrolního dne „${note.title}“ ze dne ${String(note.meeting_date||'').split('-').reverse().join('. ')}.\n\nS pozdravem\nEKV Project s.r.o.`}));
 const html=useMemo(()=>meetingPrintHtml(note,{entityTitle,entityType,entityCode}),[note,entityTitle,entityType,entityCode]);
 const print=()=>{try{setError('');if(!frame.current?.contentWindow)throw new Error();frame.current.contentWindow.focus();frame.current.contentWindow.print();}catch{setError('Tisk se nepodařilo otevřít.');}};
 const prepare=async(openEmail=false)=>{setBusy(true);setError('');try{const value=prepared||await saveMeetingNotePdf({note,entityTitle,entityType,entityId,entityCode});setPrepared(value);setEmailOpen(openEmail);onChanged?.();return value;}catch(e){setError(e.message||'PDF se nepodařilo vytvořit a uložit.');return null;}finally{setBusy(false);}};
 const send=async()=>{const recipients=parseRecipients(mail.recipients);if(!recipients.length){setError('Zadejte alespoň jeden e-mail příjemce.');return;}setBusy(true);setError('');try{const value=prepared||await saveMeetingNotePdf({note,entityTitle,entityType,entityId,entityCode});setPrepared(value);await sendMeetingNotePdf({prepared:value,recipients,subject:mail.subject,message:mail.message});setEmailOpen(false);onChanged?.();}catch(e){setError(e.message||'E-mail se nepodařilo odeslat.');}finally{setBusy(false);}};
 return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="flex h-[92vh] max-w-5xl flex-col gap-3 overflow-hidden"><DialogHeader><DialogTitle>Zápis z KD · verze {note.version}</DialogTitle><DialogDescription>Firemní PDF se při exportu uloží do složky zápisů s datem a verzí v názvu. Potom jej můžete rovnou odeslat.</DialogDescription></DialogHeader>
 <div className="flex flex-wrap items-center gap-2">{canEdit&&<><Button onClick={()=>prepare(false)} disabled={busy}>{busy?'Zpracovávám…':prepared?'PDF uloženo':'Uložit PDF do složky'}</Button><Button variant="outline" onClick={()=>prepared?setEmailOpen(true):prepare(true)} disabled={busy}>Uložit a odeslat</Button></>}<Button variant="ghost" onClick={print} disabled={!ready||busy}>Tisk</Button>{prepared?.stored?.webUrl&&<Button asChild variant="ghost"><a href={prepared.stored.webUrl} target="_blank" rel="noreferrer">Otevřít uložené PDF</a></Button>}<Button variant="ghost" onClick={onClose}>Zavřít</Button></div>
 {prepared&&<p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-2 text-sm text-emerald-800">Uloženo: {prepared.fileName}</p>}{error&&<p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-2 text-sm text-red-700">{error}</p>}
 {emailOpen?<div className="grid min-h-0 flex-1 gap-4 overflow-y-auto rounded-xl border bg-slate-50 p-4 lg:grid-cols-2"><div className="space-y-4"><div><Label>Příjemci</Label><Input value={mail.recipients} onChange={e=>setMail({...mail,recipients:e.target.value})} placeholder="klient@example.cz"/></div><div><Label>Předmět</Label><Input value={mail.subject} onChange={e=>setMail({...mail,subject:e.target.value})}/></div><div><Label>Zpráva</Label><Textarea className="min-h-48" value={mail.message} onChange={e=>setMail({...mail,message:e.target.value})}/></div><div className="flex gap-2"><Button onClick={send} disabled={busy||!mail.subject.trim()||!mail.message.trim()}>{busy?'Odesílám…':'Odeslat PDF'}</Button><Button variant="outline" onClick={()=>setEmailOpen(false)} disabled={busy}>Zpět na náhled</Button></div></div><iframe title="Náhled zápisu před odesláním" srcDoc={html} className="hidden h-full min-h-[520px] w-full rounded-lg border bg-white lg:block"/></div>:<iframe ref={frame} title={`Náhled zápisu ${note.title}, verze ${note.version}`} sandbox="allow-same-origin allow-modals" srcDoc={html} onLoad={()=>setReady(true)} className="min-h-0 w-full flex-1 rounded-lg border bg-slate-100"/>}
 </DialogContent></Dialog>;
}
