-- One-time linkage of existing portal records to pre-existing SharePoint root folders.
-- Generated by tools/discover-sharepoint-folder-links.mjs using exact code/name matching only.
-- Existing mappings are intentionally preserved.

DO $$
DECLARE
  v_connection_id uuid;
BEGIN
  SELECT id
  INTO v_connection_id
  FROM public.document_storage_connections
  WHERE provider = 'sharepoint'
    AND status = 'active'
  ORDER BY is_default DESC, created_at ASC
  LIMIT 1;

  IF v_connection_id IS NULL THEN
    RAISE EXCEPTION 'Active SharePoint storage connection was not found';
  END IF;

  INSERT INTO public.document_storage_folders (
    connection_id,
    entity_type,
    entity_id,
    folder_path,
    external_folder_id,
    external_web_url,
    status,
    metadata
  )
  VALUES
    (
      v_connection_id,
      'project',
      'd0ce06c9-00c1-4783-9c4c-63add4c748f4'::uuid,
      'OP-26-104 PD - Rohan C - Sudie střech s FVE',
      '01V7SMFCJCL3BDX3GKDRDISFKBPIXLUBRI',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-26-104%20PD%20-%20Rohan%20C%20-%20Sudie%20st%C5%99ech%20s%20FVE',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-26-104',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '923686bc-3c07-439d-8277-8d463e5027ac'::uuid,
      'OP-26-105 PD - 2x BD basic',
      '01V7SMFCKPBL43D3MZWBEY2IWYDURYGMH4',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-26-105%20PD%20-%202x%20BD%20basic',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-26-105',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      'd0f90790-0961-4d90-927c-e2351ac92d05'::uuid,
      'OP-26-059 PD - Petrovice u Sušice 105',
      '01V7SMFCIT62FOKPDDCNEZLKQXVM7BRP2H',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-26-059%20PD%20-%20Petrovice%20u%20Su%C5%A1ice%20105',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-26-059',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '4b126061-a0a6-47fd-ba75-795e588254ca'::uuid,
      'OP-26-078 PD_DPS - FVE_DOMOV PRO SENIORY – ĎÁBLICE',
      '01V7SMFCKTSPJ7FZDG7BGYABIIFTGQPTTK',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-26-078%20PD_DPS%20-%20FVE_DOMOV%20PRO%20SENIORY%20%E2%80%93%20%C4%8E%C3%81BLICE',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-26-078',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '77d3a7a8-a0f5-4a68-8088-64bec17c4a99'::uuid,
      'OP-26-071 FVE  - ČD STAVBA NOVÉ SKLADOVACÍ HALY',
      '01V7SMFCN2MK2RKHHKO5EYDKDFIB7K4EDO',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-26-071%20FVE%20%20-%20%C4%8CD%20STAVBA%20NOV%C3%89%20SKLADOVAC%C3%8D%20HALY',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-26-071',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '5ab2f212-c9f6-4ba1-b495-99cc9d635c69'::uuid,
      'OP-26-060 - Vzorový projekt FVE 11,2kwp',
      '01V7SMFCMZKI4VZNPJXNF2BZORKFM2EPOV',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-26-060%20-%20Vzorov%C3%BD%20projekt%20FVE%2011,2kwp',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-26-060',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '6f1c7910-69ae-48f7-9363-39294607247c'::uuid,
      'OP-26-029 PD - FVE 2026_1',
      '01V7SMFCP435DNJLZWENE2K2FJBGV7LAEI',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-26-029%20PD%20-%20FVE%202026_1',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-26-029',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '73cf8fbe-d4c5-4128-be27-4b29bc4d83b3'::uuid,
      'OP-26-028 Dostupné bydlení v Radnicích',
      '01V7SMFCPE3UJXX26N7ZF2RHACTDZCMZL3',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-26-028%20Dostupn%C3%A9%20bydlen%C3%AD%20v%20Radnic%C3%ADch',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-26-028',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      'afd1abf1-b78c-4396-abf1-c71572e08de6'::uuid,
      'OP-26-006 FVE - Sokolovna Rychnov',
      '01V7SMFCLV5KTPQE76DVDKV3A7C5VN6BUV',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-26-006%20FVE%20-%20Sokolovna%20Rychnov',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-26-006',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '66ee99f6-f705-4cac-8236-5e843298eb9e'::uuid,
      'OP-25-188 PD - SVR Klatovy DPZ',
      '01V7SMFCIB46JUXQUHHRDYQZCCLALWZ5CW',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-25-188%20PD%20-%20SVR%20Klatovy%20DPZ',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-188',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '9f255e64-241f-4429-afa6-8dde533d811c'::uuid,
      'OP-25-187 BESS -  Papírna ML',
      '01V7SMFCJR5CICEVNE75HLSOZZ6VPFSUUV',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-25-187%20BESS%20-%20%20Pap%C3%ADrna%20ML',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-187',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      'd872a77b-004d-4662-b83d-6ad01c14d4a7'::uuid,
      'OP-25-191 PD - NAB. INF. Beranka',
      '01V7SMFCM3HVFQ7FICUVGKQGBYOJUKOGM5',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-25-191%20PD%20-%20NAB.%20INF.%20Beranka',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-191',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '352369c4-fa99-4a01-8296-5753b9180e1e'::uuid,
      'OP-25-177 BAT-  Trutnov',
      '01V7SMFCI6D3FNHNWCGBGK34R7BIR43JTS',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-25-177%20BAT-%20%20Trutnov',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-177',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      'f1270a2d-f35a-4aa5-8ba4-c5fc659a4019'::uuid,
      'OP-25-184 DPS FVE  -  PICH',
      '01V7SMFCOLCOHMC7FOGVFZDVKCWIG4QIQY',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-25-184%20DPS%20FVE%20%20-%20%20PICH',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-184',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '0b0bd9b3-f54f-4d30-8dea-c891950fb1d4'::uuid,
      'OP-25-169 TES - ORLEN 7',
      '01V7SMFCO66WW6ZPO4UNBIXHLRMGWD225P',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-25-169%20TES%20-%20ORLEN%207',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-169',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      'f14da1d1-fc81-41d8-94b9-4a25b665a878'::uuid,
      'OP-25-176 PD - FVE Fuhrmann Medical 2',
      '01V7SMFCNISKQNZQX7BBBZFAUYYARFLFHG',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-25-176%20PD%20-%20FVE%20Fuhrmann%20Medical%202',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-176',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '4a4610ea-c021-4f99-a207-a040b2549b03'::uuid,
      'OP-25-155 ST  - BESS Radnice',
      '01V7SMFCJPEEOGDPQL7FEZYEFLYUZNDE64',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-25-155%20ST%20%20-%20BESS%20Radnice',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-155',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '97d13744-dc5a-4fd3-9d5c-44448ed14c99'::uuid,
      'PRO-25-011 PD - 6 Orlen FVE,BESS,NAB',
      '01V7SMFCIN4SXFDTCJLFHZ2S2QOS25D5QJ',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/PRO-25-011%20PD%20-%206%20Orlen%20FVE,BESS,NAB',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'PRO-25-011',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '27bf81d8-1dc9-40ae-b8a7-4cbd5aaf9f20'::uuid,
      'OP-25-156 PD - PŘÍSTAV SLOVÁCKO (ŘVC)',
      '01V7SMFCN6JGY2SYL7VBDZGXGIFNEMU7P3',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-25-156%20PD%20-%20P%C5%98%C3%8DSTAV%20SLOV%C3%81CKO%20(%C5%98VC)',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-156',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      'e472b98f-0288-42a3-8f52-be25b0ddeed3'::uuid,
      'OP-24-233_České_Velenice',
      '01V7SMFCK5P2SZIBVDWBFZNVDB4722ZNNR',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-24-233_%C4%8Cesk%C3%A9_Velenice',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-24-233',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      'a65dfa7d-412c-420a-82bf-14aafeb63bfa'::uuid,
      'OP-25-026 PD -  (DPS) FVE Mrazírny Eurofrost',
      '01V7SMFCKXU3B7LZ2IVFEZLR4DJMITGEGF',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-25-026%20PD%20-%20%20(DPS)%20FVE%20Mraz%C3%ADrny%20Eurofrost',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-026',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '01ea39fe-3753-4551-a4b1-0e6875e91883'::uuid,
      'OP-25-094 FVE - FVE 400kWp, Mantov',
      '01V7SMFCJQ4MFDJEMIO5FLQDMLW3QPOR7U',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-25-094%20FVE%20-%20FVE%20400kWp,%20Mantov',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-094',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '5aa6ea20-5f3b-4545-9a28-4e80d2a180dc'::uuid,
      'OP-25-149 FVE  - ŽST Valašské Meziříčí',
      '01V7SMFCLU3R3UXGSBFJFI4W3CKJOL5HKP',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-25-149%20FVE%20%20-%20%C5%BDST%20Vala%C5%A1sk%C3%A9%20Mezi%C5%99%C3%AD%C4%8D%C3%AD',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-149',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      '6e2e589c-e2ef-4191-9710-08076ad72a85'::uuid,
      'OP-24-274 PD -Tradiční pivovar v Rakovníku',
      '01V7SMFCPLLWVUZHSX6BDY2C6632C5SQXE',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-24-274%20PD%20-Tradi%C4%8Dn%C3%AD%20pivovar%20v%20Rakovn%C3%ADku',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-24-274',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      'cf601647-dbb7-4d52-a1b2-a9b6de739503'::uuid,
      'OP-25-013 PD - Continetnal',
      '01V7SMFCIIM4NCGBBCINE2LIRMAFHM5KJO',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-25-013%20PD%20-%20Continetnal',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-013',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'project',
      'd43c9823-19b1-4185-bf54-f18d64b3aebb'::uuid,
      'OP-25-098 eHUB - IVANOVICE NA HANÉ',
      '01V7SMFCJ2I3NNO33OQFFYGKDAORF34Q52',
      'https://ekvproject.sharepoint.com/sites/project/Shared%20Documents/OP-25-098%20eHUB%20-%20IVANOVICE%20NA%20HAN%C3%89',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-098',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'realizace',
      'efee5845-3ad7-40df-8f6a-1609bf1d48d4'::uuid,
      'OP-26-005 FVE - Psovské údolí, Palis',
      '01THPRNHKBP6MSB2RXKBEYOV7W3FXEO7YG',
      'https://ekvproject.sharepoint.com/sites/Realizace/Shared%20Documents/OP-26-005%20FVE%20-%20Psovsk%C3%A9%20%C3%BAdol%C3%AD,%20Palis',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-26-005',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'realizace',
      '55462f29-056b-49cb-8f3b-97a2c809a2f3'::uuid,
      'OP-26-069 FVE - Volary',
      '01THPRNHMJ3H3GSEBCLJGZUHKGKBTRDKTR',
      'https://ekvproject.sharepoint.com/sites/Realizace/Shared%20Documents/OP-26-069%20FVE%20-%20Volary',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-26-069',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'realizace',
      'dda7b688-ce2d-4e41-9b57-26c719ccb940'::uuid,
      'OP-23-139 FVE - Varia Plus',
      '01THPRNHK5WU6ZPS6U65GKD5A4NJBAXHOX',
      'https://ekvproject.sharepoint.com/sites/Realizace/Shared%20Documents/OP-23-139%20FVE%20-%20Varia%20Plus',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-23-139',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'realizace',
      '1db042ff-b0ac-4be3-a5e8-b2acd10c0311'::uuid,
      'OP-23-074 FVE - Praní a čištění, s.r.o. 99kWp',
      '01THPRNHODLI3CINZDUVFYXJBPZWLYKUYL',
      'https://ekvproject.sharepoint.com/sites/Realizace/Shared%20Documents/OP-23-074%20FVE%20-%20Pran%C3%AD%20a%20%C4%8Di%C5%A1t%C4%9Bn%C3%AD,%20s.r.o.%2099kWp',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-23-074',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'realizace',
      'c2066050-9ad6-410b-af86-12c933c7c1ab'::uuid,
      'OP-25-151 FVE - OTV Plzeň',
      '01THPRNHLZFZB3XPHTHNDJXQAEAG2XAQJ3',
      'https://ekvproject.sharepoint.com/sites/Realizace/Shared%20Documents/OP-25-151%20FVE%20-%20OTV%20Plze%C5%88',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-151',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'realizace',
      'a07a035e-44ae-4f78-a45f-66c5f5094e2b'::uuid,
      'OP-25-106 FVE - Kostelec (VZ)',
      '01THPRNHIZLPZATGCABVFZZGMVUWXPMFIC',
      'https://ekvproject.sharepoint.com/sites/Realizace/Shared%20Documents/OP-25-106%20FVE%20-%20Kostelec%20(VZ)',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-106',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'realizace',
      'd9775fdc-9db4-4d4c-a6d8-e2abb3996491'::uuid,
      'OP-25-014 FVE - MŠ ÚJEZD II',
      '01THPRNHKG3I5RNSESF5B2IRSGB6GW4OGC',
      'https://ekvproject.sharepoint.com/sites/Realizace/Shared%20Documents/OP-25-014%20FVE%20-%20M%C5%A0%20%C3%9AJEZD%20II',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-25-014',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    ),
    (
      v_connection_id,
      'realizace',
      'cf1e58d2-5af7-474e-9642-6c942ec26116'::uuid,
      'OP-24-251 FVE - Kärcher Center Modletice u Prahy',
      '01THPRNHIKN4SJJ57MGRFZ36UWPWVVS4TU',
      'https://ekvproject.sharepoint.com/sites/Realizace/Shared%20Documents/OP-24-251%20FVE%20-%20K%C3%A4rcher%20Center%20Modletice%20u%20Prahy',
      'created',
      jsonb_build_object(
        'backfilled', true,
        'legacyFolder', true,
        'matchedBy', 'exact_code',
        'recordCode', 'OP-24-251',
        'source', 'sharepoint-root-folder-backfill-2026-07-13'
      )
    )
  ON CONFLICT (connection_id, entity_type, entity_id) DO NOTHING;
END $$;
